export default {
  APP_INIT: 'APP/APP_INIT',
  SHOW_SNACKBAR: 'SNACKBAR/SHOW_SNACKBAR',
  CLOSE_SNACKBAR: 'SNACKBAR/CLOSE_SNACKBAR',
  SHOW_BACKDROP: 'BACKDROP/SHOW_BACKDROP',
  CLOSE_BACKDROP: 'BACKDROP/CLOSE_BACKDROP',
  CHANGE_HELMET: 'HELMET/CHANGE_HELMET',
  SHOW_CONFIRM: 'DIALOG/SHOW_CONFIRM',
  CLOSE_CONFIRM: 'DIALOG/CLOSE_CONFIRM'
}
